rm -rf ./files/alacritty.yml
rm -rf ./files/i3config
rm -rf ./files/nvim
rm -rf ./files/picom.conf
rm -rf ./files/polybarconfig
rm -rf ./files/rofi
rm -rf ./files/.tmux.conf
rm -rf ./files/.tmux.conf.local
rm -rf ./files/.zshrc
rm -rf ./files/kubecompletion.sh
