rm -rf ./files/alacritty
rm -rf ./files/i3config
rm -rf ./files/nvim
rm -rf ./files/picom.conf
rm -rf ./files/polybarconfig
rm -rf ./files/rofi
rm -rf ./files/tmux
rm -rf ./files/.zshrc
rm -rf ./files/kubecompletion.sh
rm -rf ./files/ghcompletion.sh
