force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
click_to_close = true           # closes walker if clicking outside of the main content area
selection_wrap = false          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
exact_search_prefix = "'"       # disable fuzzy searching
disable_mouse = false           # disable mouse (on input and list only)
additional_theme_location = "~/.config/walker/themes/"

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" }
"menus:menu" = { input = "Search", list = "No Results" }

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]
quick_activate = []

[providers]
default = [
  "desktopapplications"
]
empty = ["desktopapplications"]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "!"
provider = "todo"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[providers.actions]
dmenu = [
 { action = "select", default = true, bind = "Return" },
 { action = "provider:menus:menu", bind = "ctrl x", global = true, after = "ClearReload" },
]

providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" },
]

"menus:menu" = [
  { action = "lock", bind = "Return" },
  { action = "suspend", bind = "Return" },
  { action = "logout", bind = "Return" },
  { action = "restart", bind = "Return" },
  { action = "shutdown", bind = "Return" },
  { action = "provider:menus:menu", bind = "ctrl x", global = true, after = "ClearReload" },
]

